data_preprocessing:
  raw_data_file: "data/raw/credit_risk_dataset.csv"
  train_file: "data/processed/train.csv"
  test_file: "data/processed/test.csv"
  target: "loan_status"
  test_size: 0.3
  random_state: 42

train:
  train_file: "data/processed/train.csv"
  woe_transformer_params: {
    "numerical_columns": ["person_age", "person_income", "person_emp_length", "loan_amnt", "loan_int_rate", "loan_percent_income", "cb_person_cred_hist_length"],
    "categorical_columns": ["person_home_ownership", "loan_intent", "loan_grade", "cb_person_default_on_file"],
    "bins": 5
  }
  logreg_params: {"random_state": 42}
  model_file: "models/woe_lr.pickle"
  target: "loan_status"
  test_file: "data/processed/test.csv"

evaluate:
  train_file: "data/processed/train.csv"
  test_file: "data/processed/test.csv"
  model_file: "models/woe_lr.pickle"
  target: "loan_status"
  train_metrics_file: "reports/train_metrics.json"
  test_metrics_file: "reports/test_metrics.json"
  train_calibration_curve_file: "reports/figures/train_calibration_curve.png"
  test_calibration_curve_file: "reports/figures/test_calibration_curve.png"

inference:
  model_file: "models/woe_lr.pickle"
  pdo: 20
  odds: 1
  scorecard_points: 500